language: php

php: [5.3]

env:
  - SF_VERSION='~2.3'
  - SF_VERSION='~2.4'

before_script:
  - export WEB_FIXTURES_HOST=http://localhost/index.php

  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 4

  - curl http://getcomposer.org/installer | php
  - php composer.phar require --no-update symfony/symfony=$SF_VERSION
  - php composer.phar install --dev

  - Tests/app/console assets:install Tests/app
  - sudo chmod -R 0777 Tests/app/cache Tests/app/logs
  - sudo chmod 0777 Resources/public/js/fp_js_validator.js
  - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'

  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 > /dev/null

  - sudo sed -i -e "s,/var/www,$(pwd)/Tests/app,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart

  - curl http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar > selenium.jar
  - java -jar selenium.jar > selenium.log &
  - sleep 4

script: phpunit -v
after_script:
  - php vendor/bin/coveralls -v
after_failure:
  - cat selenium.log